apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: <ACCOUNT-ID>.dkr.ecr.<REGION-CODE>.amazonaws.com/product:latest # Replace with your actual image name and tag
        ports:
        - containerPort: 3002
        env:
        - name: SECRET
          value: "<JWT_SECRET_VALUE>"
        - name: DATABASE_URL
          value: "<RDS_LINK>"