apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: <ACCOUNT-ID>.dkr.ecr.<REGION-CODE>.amazonaws.com/product:latest  # Replace with your actual image name and tag
        ports:
        - containerPort: 3001
        env:
        - name: SECRET
          value: "<JWT_SECRET_VALUE>"
        - name: DATABASE_URL
          value: "<RDS_LINK>"